name: Release

on:
  push:
    branches:
      - master

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Releases
      uses: thefrontside/actions/synchronize-with-npm@v1.6
      with:
        npm_publish: npm publish --access=public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.FRONTSIDEJACK_NPM_TOKEN }}
